version: '3'

services:
  mysql:
    image: mysql
    container_name: myDB
    volumes:
      - "./init.sql:/docker-entrypoint-initdb.d/1.sql"
    environment:
      MYSQL_ROOT_PASSWORD: password

  php-apache:
    build:
      "/"
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
    depends_on:
      - mysql
